-- 50 catégories de métiers locaux (les 6 du seed sont conservées via on conflict).
insert into public.categories (slug, name_fr, name_en, icon) values
  ('plombier',          'Plombier',                 'Plumber',              'droplet'),
  ('serrurier',         'Serrurier',                'Locksmith',            'lock'),
  ('electricien',       'Électricien',              'Electrician',          'lightbulb'),
  ('macon',             'Maçon',                    'Mason',                'hammer'),
  ('restaurant',        'Restaurant',               'Restaurant',           'utensils'),
  ('coiffeur',          'Coiffeur',                 'Hairdresser',          'scissors'),
  ('menuisier',         'Menuisier',                'Carpenter',            'ruler'),
  ('peintre',           'Peintre en bâtiment',      'Painter',              'paintbrush'),
  ('carreleur',         'Carreleur',                'Tiler',                'grid'),
  ('chauffagiste',      'Chauffagiste',             'Heating engineer',     'flame'),
  ('jardinier',         'Jardinier',                'Gardener',             'sprout'),
  ('paysagiste',        'Paysagiste',               'Landscaper',           'trees'),
  ('dentiste',          'Dentiste',                 'Dentist',              'stethoscope'),
  ('medecin',           'Médecin généraliste',      'General practitioner', 'stethoscope'),
  ('veterinaire',       'Vétérinaire',              'Veterinarian',         'paw'),
  ('pharmacie',         'Pharmacie',                'Pharmacy',             'pill'),
  ('kinesitherapeute',  'Kinésithérapeute',         'Physiotherapist',      'heart-pulse'),
  ('opticien',          'Opticien',                 'Optician',             'glasses'),
  ('avocat',            'Avocat',                   'Lawyer',               'scale'),
  ('notaire',           'Notaire',                  'Notary',               'stamp'),
  ('comptable',         'Comptable',                'Accountant',           'calculator'),
  ('architecte',        'Architecte',               'Architect',            'ruler'),
  ('agent-immobilier',  'Agent immobilier',         'Real estate agent',    'building'),
  ('boulangerie',       'Boulangerie',              'Bakery',               'croissant'),
  ('patisserie',        'Pâtisserie',               'Pastry shop',          'cake'),
  ('boucherie',         'Boucherie',                'Butcher',              'beef'),
  ('fleuriste',         'Fleuriste',                'Florist',              'flower'),
  ('epicerie',          'Épicerie',                 'Grocery store',        'basket'),
  ('cafe',              'Café',                     'Coffee shop',          'coffee'),
  ('bar',               'Bar',                      'Bar',                  'wine'),
  ('hotel',             'Hôtel',                    'Hotel',                'bed'),
  ('garage',            'Garage automobile',        'Auto garage',          'car'),
  ('carrossier',        'Carrossier',               'Body shop',            'car'),
  ('taxi',              'Taxi / VTC',               'Taxi & ride',          'car'),
  ('demenagement',      'Déménagement',             'Moving company',       'truck'),
  ('transport',         'Transport / Logistique',   'Transport',            'truck'),
  ('nettoyage',         'Société de nettoyage',     'Cleaning company',     'sparkles'),
  ('pressing',          'Pressing',                 'Dry cleaner',          'shirt'),
  ('cordonnerie',       'Cordonnerie',              'Shoe repair',          'footprints'),
  ('salle-de-sport',    'Salle de sport',           'Gym',                  'dumbbell'),
  ('coach-sportif',     'Coach sportif',            'Personal trainer',     'dumbbell'),
  ('yoga',              'Studio de yoga',           'Yoga studio',          'activity'),
  ('esthetique',        'Institut de beauté',       'Beauty salon',         'sparkles'),
  ('spa',               'Spa & bien-être',          'Spa & wellness',       'flower'),
  ('tatoueur',          'Tatoueur',                 'Tattoo artist',        'brush'),
  ('photographe',       'Photographe',              'Photographer',         'camera'),
  ('imprimerie',        'Imprimerie',               'Print shop',           'printer'),
  ('informatique',      'Dépannage informatique',   'IT support',           'laptop'),
  ('telephonie',        'Réparation mobile',        'Phone repair',         'smartphone'),
  ('assurance',         'Assurance',                'Insurance',            'umbrella')
on conflict (slug) do nothing;
